# Copyright 2023 The OpenVEX Authors
# SPDX-License-Identifier: Apache-2.0

name: Boilerplate

on:
  pull_request:
    branches:
      - 'main'
      - 'release-*'

jobs:

  check:
    name: Boilerplate Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        extension:
          - go
          - sh
          - yaml

        # Map between extension and human-readable name.
        include:
          - extension: go
            language: Go
          - extension: sh
            language: Bash
          - extension: yaml
            language: YAML
          - extension: yml
            language: YAML

    steps:
      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: chainguard-dev/actions/boilerplate@main
        with:
          extension: ${{ matrix.extension }}
          language: ${{ matrix.language }}
